// do not edit this file nless you know exactly what you are doing
module.exports = ({ htmlWebpackPlugin }) => {
  return `
    <!doctype html>
      <html lang="${htmlWebpackPlugin.options.lang || 'en'}">
      <head>
        <meta charset="UTF-8">
        <title>${htmlWebpackPlugin.options.title}</title>
      </head>
      <body>
        <div id="root">${htmlWebpackPlugin.options.body ? require('' + htmlWebpackPlugin.options.body) : ''}</div>
      </body>
    </html>
  `
}
