name: Tag
on:
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag application
        uses: actions/setup-node@v1
        run: yarn release
        if: github.ref == 'refs/heads/main'
