name: Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: yarn install

      - name: Lint
        run: |
          yarn format:scss
          yarn check-git
          yarn lint:js
          yarn lint:scss

      - name: Test
        run: yarn test

      - name: PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint
